### ISSUE TITLE
Undefined in title of browser for a second

### ISSUE THREAD

**Issue by sandeepscet** [sandeepscet/prompt-apps#12]
![image](https://user-images.githubusercontent.com/1390862/235622281-097a44dd-cdc5-4e23-b3c7-95ee012f6951.png)

- When the user tries to open any app or category.
- This may create problem in SEO

**Comment by sandeepscet** [comment]
@meljason Please check this

**Comment by meljason** [comment]
Will check now :)

**Comment by meljason** [comment]
Please check my PR.
